### ISSUE TITLE
JavaFX classes cannot be loaded: hook needed

### ISSUE THREAD

**Issue by Dierk** [Frege/native-gen#16]
JavaFX classes cannot be loaded out of context. We need some kind of hook to start the whole process inside com.sun.javafx.application.PlatformImpl.runLater.

Stack trace:

java -jar native-gen-1.0-SNAPSHOT.jar javafx.scene.control.Button 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	..
	at frege.nativegen.Main.main(Main.java:737)
Caused by: java.lang.IllegalStateException: Toolkit not initialized
	at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:273)
	..
	at javafx.scene.control.Control.<clinit>(Control.java:87)

**Comment by mmhelloworld** [comment]
This was caused by class initialization by using `Class.forName(String)` to obtain the class object. I fixed it by using the other variant `Class.forName(String name, boolean initialize, ClassLoader loader)`. The new jar with this fix is available in the releases page.

**Comment by Dierk** [comment]
cool, thanks!
